language: python   #设置语言

install: true

before_script:
  - git clone https://github.com/tiny656/PAT.git

script:
  - echo 'script'

after_script:
  - cd PAT
  - python READMEBuild.py
  - git config user.name "tiny656"   #修改成自己的github用户名
  - git config user.email "tiny656@hotmail.com"   #修改成自己的GitHub邮箱
  - git add .
  - git commit -m "[skip ci]update README.md by Travis-CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
  - master

env:
  global:
  - GH_REF: github.com/tiny656/PAT.git
